name=PlaneteSciences85
version=1.0.0
author=Adrien Legrand <contact@adrien-legrand.com>
maintainer=Adrien Legrand <contact@adrien-legrand.com>
sentence=A library that provides high level examples for discovering electronics through simple projects.
paragraph=Includes Kamishibai class to abtract audio, SD and lights controls.
category=Signal Input/Output
url=https://github.com/Adrien-Legrand/PlaneteSciences85
architectures=avr
includes=Kamishibai.h
depends=Adafruit VS1053 Library,PololuLedStrip